title: Nautilus
description: A Units of Measure library for .Net Standard
baseurl: "/NautilusUnits" # the subpath of your site, e.g. /blog
url: "https://qkmaxware.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

highlighter: rouge

collections:
  posts: 
    output: true
    permalink: /posts/:year/:month/:day/:title
  downloads:
    output: false
  features:
    output: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
