name: Build
on:
  push: 
    branches: 
    - "master"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: docker://mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run Unit Tests
      working-directory: ${{ github.workspace }}
      run: dotnet test Units.Tests
    - name: Run Examples
      working-directory: ${{ github.workspace }}
      run: dotnet run Units.Examples
  build:
    name: Build & Pack
    runs-on: ubuntu-latest
    container: 
      image: docker://mcr.microsoft.com/dotnet/core/sdk:3.0
    needs: [ Test ]
    steps: 
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      working-directory: ${{ github.workspace }}
      run: dotnet build Units
    - name: Pack
      working-directory: ${{ github.workspace }}
      run: dotnet pack Units
