name: Build
on:
  push: 
    branches: 
    - "master"
jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Run Unit Tests
      run: dotnet test Units.Tests
    - name: Run Examples
      run: dotnet run --project Units.Examples
    - name: Build
      run: dotnet build --configuration Release Units
    - name: Pack
      run: dotnet pack --configuration Release Units
