name: Build
on:
  push: 
    branches: 
    - "master"
jobs:
  test-build:
    name: Test and Build
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix: 
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
        dotnet: [ '3.0.100' ]
    steps:
    - name: Checkout Code - ${{ matrix.os }}
      uses: actions/checkout@master
    - name: Setup .NET Core - ${{ matrix.dotnet }}@${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ matrix.dotnet }}'
    - name: .Net Core Info
      run: dotnet --info
    - name: Run Unit Tests - ${{ matrix.os }}
      run: dotnet test Units.Tests
    - name: Run Examples - ${{ matrix.os }}
      env: 
        DOTNET_ROOT: ${env:DOTNET_ROOT}/${{ matrix.dotnet }}/x64/
      run: dotnet run --project Units.Examples
    - name: Build - ${{ matrix.os }}
      env: 
        DOTNET_ROOT: ${env:DOTNET_ROOT}/${{ matrix.dotnet }}/x64/
      run: dotnet build --configuration Release Units