name: Build
on:
  push: 
    branches: 
    - "master"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Run Unit Tests
      run: dotnet test Units.Tests
    - name: Run Examples
      run: dotnet run --project Units.Examples
  build:
    name: Build & Pack
    runs-on: ubuntu-latest
    needs: [ Test ]
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Build
      run: dotnet build Units
    - name: Pack
      run: dotnet pack Units
