name: Build
on:
  push: 
    branches: 
    - "master"
jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
    - name: Run Unit Tests
      run: dotnet test Units.Tests
    - name: Run Examples
      run: dotnet run --project Units.Examples
    - name: Build
      run: dotnet build Units
    - name: Pack
      run: dotnet pack Units
