name: Build
on:
  push: 
    branches: 
    - "master"
jobs:
  test:
    name: Test
    container: 
      image: docker://mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
    - name: Run Unit Tests
      run: dotnet test Units.Tests
    - name: Run Examples
      run: dotnet run Units.Examples
  build:
    name: Build & Pack
    container: 
      image: docker://mcr.microsoft.com/dotnet/core/sdk:3.0
    needs: [ Test ]
    steps: 
    - name: Build
      run: dotnet build Units
    - name: Pack
      run: dotnet pack Units
