name: Publish
on: 
  deployment:
    branches: 
    - "master"
jobs:
  publish:
    name: Pack & Publish
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
    - name: Pack
      run: dotnet pack Units
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_SOURCE: https://nuget.pkg.github.com/qkmaxware/index.json
      run: dotnet nuget push Units --api-key ${GITHUB_TOKEN} --source ${GITHUB_SOURCE}