name: Publish
on: 
  deployment:
    branches: 
    - "master"
jobs:
  publish:
    name: Pack & Publish
    runs-on: ubuntu-latest
    container: 
      image: docker://mcr.microsoft.com/dotnet/core/sdk:3.0
    steps: 
    - name: Checkout
      uses: actions/checkout@v1
    - name: Pack
      run: dotnet pack /home/runner/work/CsUnits/CsUnits/Units
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_SOURCE: https://nuget.pkg.github.com/qkmaxware/index.json
      run: dotnet nuget push Units --api-key ${GITHUB_TOKEN} --source ${GITHUB_SOURCE}